# This is a YAML-formatted file to set or update certain parameters to get a very basic app up and running in the sandbox.
# Declare variables to be passed into your templates.

sandbox:
  user: "your-name"

pod:
  images:
    - name: "cabinternational/k8s-demo"
      tag: "refresh-test"
      probes:
        ready: /health/kubernetes
        liveness: /health/kubernetes
      configMaps:
        - name: config-for-refresh
          mount: /app/RefreshableData
        - name: config-for-reload
          mount: /app/NonRefreshableData

ingress:
  affinity: persistent
  restrictToCabi: false
